title: Korea MCT Summit
description: > # this means to ignore newlines until "baseurl:"
  Microsoft 기술을 가르치는 강사들의 성장과 교류를 위한 행사 
baseurl: "" # the subpath of your site, e.g. /blog
url: "koreamct.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "/css/2016_style/img/icon-mct-badge.png"

social: 
  name: Korea MCT Facebook Group
  link: "https://www.facebook.com/groups/koreamct"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['2025', '2026']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/groups/koreamct
  # - title: twitter
  #   url: https://twitter.com

# Build settings
markdown: kramdown
permalink: pretty