title: Korea MCT
description: > # this means to ignore newlines until "baseurl:"
  한국에서 활동하는 MCT(Microsoft Certified Trainer)를 위한 커뮤니티
baseurl: "" # the subpath of your site, e.g. /blog
url: "koreamct.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "/css/2017_style/img/logos/MCT-badge.png"

social: 
  name: Korea MCT Facebook Group
  link: "https://www.facebook.com/groups/koreamct"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['2025', '2026']

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/groups/koreamct
  # - title: twitter
  #   url: https://twitter.com

# Build settings
markdown: kramdown
permalink: pretty